servers:
- name: dc1-leaf1-server1
  adapters:
  - endpoint_ports:
    - Ethernet1
    - Ethernet2
    switch_ports:
    - Ethernet5
    - Ethernet5
    switches:
    - dc1-leaf1a
    - dc1-leaf1b
    vlans: 11-12,21-22
    native_vlan: 4092
    mode: trunk
    spanning_tree_portfast: edge
    port_channel:
      description: PortChannel dc1-leaf1-server1
      mode: active
- name: dc1-leaf2-server1
  adapters:
  - endpoint_ports:
    - Ethernet1
    - Ethernet2
    switch_ports:
    - Ethernet5
    - Ethernet5
    switches:
    - dc1-leaf2a
    - dc1-leaf2b
    vlans: 11-12,21-22
    native_vlan: 4092
    mode: trunk
    spanning_tree_portfast: edge
    port_channel:
      mode: active
- name: dc2-leaf1-server1
  adapters:
  - endpoint_ports:
    - Ethernet1
    - Ethernet2
    switch_ports:
    - Ethernet5
    - Ethernet5
    switches:
    - dc2-leaf1a
    - dc2-leaf1b
    vlans: 11-12,21-22
    native_vlan: 4092
    mode: trunk
    spanning_tree_portfast: edge
    port_channel:
      endpoint_port_channel: Bond1
      mode: active
- name: dc2-leaf2-server1
  adapters:
  - endpoint_ports:
    - Ethernet1
    - Ethernet2
    switch_ports:
    - Ethernet5
    - Ethernet5
    switches:
    - dc2-leaf2a
    - dc2-leaf2b
    vlans: 11-12,21-22
    native_vlan: 4092
    mode: trunk
    spanning_tree_portfast: edge
    port_channel:
      mode: active
- name: form-testing-server
  adapters:
  - endpoint_ports:
    - Ethernet1
    - Ethernet2
    switch_ports:
    - Ethernet10
    - Ethernet11
    switches:
    - dc1-leaf1a
    - dc1-leaf1b
    vlans: '200'
    native_vlan: 4092
    mode: trunk
    spanning_tree_portfast: edge
    port_channel:
      mode: active
- name: dc1-server3
  adapters:
  - endpoint_ports:
    - Ethernet1
    - Ethernet2
    switch_ports:
    - Ethernet10
    - Ethernet11
    switches:
    - dc1-leaf2a
    - dc1-leaf2b
    vlans: '200'
    native_vlan: 4092
    mode: trunk
    spanning_tree_portfast: edge
    port_channel:
      mode: active
routers:
- name: dc1-lf-edge1
  adapters:
  - endpoint_ports:
    - Etherent1
    switches:
    - dc1-leaf2a
    switch_ports:
    - Ethernet9
- name: dc1-lf-edge2
  adapters:
  - endpoint_ports:
    - Etherent1
    switches:
    - dc1-leaf2b
    switch_ports:
    - Ethernet9
- name: dc2-lf-edge1
  adapters:
  - endpoint_ports:
    - Etherent1
    switches:
    - dc2-leaf2a
    switch_ports:
    - Ethernet9
- name: dc2-lf-edge2
  adapters:
  - endpoint_ports:
    - Etherent1
    switches:
    - dc2-leaf2b
    switch_ports:
    - Ethernet9
