servers:
- name: form-testing-server
  adapters:
  - endpoint_ports:
    - Ethernet1
    - Ethernet2
    switch_ports:
    - Ethernet10
    - Ethernet11
    switches:
    - dc1-leaf1a
    - dc1-leaf1b
    vlans: '100'
    native_vlan: 4092
    mode: trunk
    spanning_tree_portfast: edge
    port_channel:
      mode: active
